In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("train_set.csv",delimiter=",",encoding='latin-1')

In [6]:
data = df.as_matrix()
data

/home/linux/anaconda3/envs/my_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[85389000, ' pdscpm gb part of panel of chiller'],
       [85389000,
        'nm  p economical extended rot hand parts for circuit breaker captive consumption'],
       [85389000, 'lv ma pd trip unit for cvs parts of circuit breakers'],
       ...,
       [84713010,
        'xfuc acj eguuqnfinnnnnues india rmn hstnnic  notebook computer not sor sale'],
       [84713010,
        ' nwg latitude  portable computernotebook assybaseumaiu pgbisr laptopnot'],
       [84713010,
        ' rpp inspiron  portable computernotebook assybasekblmy pt bisr laptop']],
      dtype=object)

In [28]:
X = data[:,1]
#print(X)

[' pdscpm gb part of panel of chiller'
 'nm  p economical extended rot hand parts for circuit breaker captive consumption'
 'lv ma pd trip unit for cvs parts of circuit breakers' ...
 'xfuc acj eguuqnfinnnnnues india rmn hstnnic  notebook computer not sor sale'
 ' nwg latitude  portable computernotebook assybaseumaiu pgbisr laptopnot'
 ' rpp inspiron  portable computernotebook assybasekblmy pt bisr laptop']


In [29]:
Y = data[:,0]
#print(Y)

[85389000 85389000 85389000 ... 84713010 84713010 84713010]


In [30]:
len(X),len(Y)

(23615, 23615)

In [32]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
Y = label.fit_transform(Y)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
count = CountVectorizer()

In [39]:
X_ = count.fit_transform(X)# generates bag-of words-model and transforms each X into a vector
#print(X_)

In [40]:
X_.shape

(23615, 13899)

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,X_test,Y_train,Y_test = train_test_split(X_,Y,test_size=0.2)

In [43]:
X_train.shape,Y_train.shape

((18892, 13899), (18892,))

In [44]:
X_test.shape,Y_test.shape

((4723, 13899), (4723,))

In [45]:
from sklearn.naive_bayes import MultinomialNB 

In [46]:
clf = MultinomialNB()

In [47]:
clf.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [48]:
clf.score(X_test,Y_test)##accuarcy when divided in train and test sets

0.881431293669278

In [49]:
#Now for the actual data trainning over the entire dataset
clf_full_data = MultinomialNB()

In [50]:
clf.fit(X_,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [51]:
###Training Accuracy in entire training set 
clf.score(X_,Y)

0.9282659326699132

In [52]:
df = pd.read_csv("test_set.csv",delimiter=",",encoding='latin-1')
X = data[:,1]

In [53]:
X = count.transform(X)

In [54]:
Y = label.inverse_transform(clf.predict(X))#prediction of Y given X

/home/linux/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [55]:
X.shape,Y.shape

((23615, 13899), (23615,))

In [56]:
print(Y)

[9 9 9 ... 3 3 3]
