In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("train_set.csv",delimiter=",",encoding='latin-1')

In [3]:
data = df.as_matrix()
#print(data)

/home/linux/anaconda3/envs/my_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [4]:
X = data[:,1] # extract text from csv file
#print(X)

In [5]:
Y = data[:,0]# it separetes label from csv file

In [6]:
print(Y)

[85389000 85389000 85389000 ... 84713010 84713010 84713010]


In [7]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
Y = label.fit_transform(Y)
print(Y)

[9 9 9 ... 3 3 3]


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
count = TfidfVectorizer() #Transforms text to feature vectors
print(count)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)


In [10]:
X_ = count.fit_transform(X)
#print(X_)

In [11]:
print(Y)
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
Y = label.fit_transform(Y)


[9 9 9 ... 3 3 3]


In [12]:
type(X_)

scipy.sparse.csr.csr_matrix

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X_,Y,test_size=0.2)## train and test splitted in 80:20 

In [15]:
X_train.shape,Y_train.shape

((18892, 13899), (18892,))

In [16]:
X_test.shape,Y_test.shape

((4723, 13899), (4723,))

In [17]:
from sklearn.naive_bayes import MultinomialNB 
clf = MultinomialNB()

In [18]:
clf.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [19]:
clf.score(X_test,Y_test)

0.89265297480415

In [20]:
#Now for the actual data trainning over the entire dataset
clf_full_data = MultinomialNB()
clf.fit(X_,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
######Training Accuracy
clf.score(X_,Y)

0.9402074952360787

In [22]:
df = pd.read_csv("test_set.csv",delimiter=",",encoding='latin-1')

In [23]:
X = df.as_matrix()[:,0]
#print(X)

/home/linux/anaconda3/envs/my_env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [24]:
X = count.transform(X)


In [25]:
Y = label.inverse_transform(clf.predict(X))#prediction of Y given X

/home/linux/anaconda3/envs/my_env/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [26]:
print(Y)

[9 9 9 ... 3 3 3]
